name: Build Go WASM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Build WASM
      run: GOOS=wasip1 GOARCH=wasm go build -o main.wasm

    - name: Upload WASM binary
      uses: actions/upload-artifact@v4
      with:
        name: wasm-binary
        path: main.wasm

    - name: Build Docker image
      run: docker build -t wasm-container .

    - name: Run Docker container
      run: |
           output=$(docker run --rm -v ${{ github.workspace }}/main.wasm:/main.wasm wasm-container)
           echo "wasm_output=$output" >> $GITHUB_OUTPUT
           echo "$output" > output.txt