name: Build Go WASM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod download

    - name: Build WASM
      run: GOOS=wasip1 GOARCH=wasm go build -o main.wasm

    - name: Upload WASM binary
      uses: actions/upload-artifact@v4
      with:
        name: wasm-binary
        path: main.wasm

    - name: Build Docker image
      run: |
        echo "FROM debian:bullseye-slim" > Dockerfile
        echo "RUN apt-get update && apt-get install -y gnupg2 curl ca-certificates && curl https://wasmtime.dev/install.sh -sSf | bash && cp /root/.wasmtime/bin/wasmtime /usr/local/bin/" >> Dockerfile
        echo "COPY main.wasm /main.wasm" >> Dockerfile
        echo 'CMD ["wasmtime", "/main.wasm"]' >> Dockerfile
        docker build -t wasm-container .

    - name: Run Docker container
      run: docker run --rm wasm-container